Fix invalid lambda captures
error C3493: 'meow' cannot be implicitly captured because no default capture mode has been specified

Signed-off-by: Osyotr <Osyotr@users.noreply.github.com>