Fix test BitStreams_Smoke
error C2338: static_assert failed: 'invalid template argument for uniform_int_distribution: N4950 [rand.req.genl]/1.5 requires one of short, int, long, long long, unsigned short, unsigned int, unsigned long, or unsigned long long'

Signed-off-by: Osyotr <Osyotr@users.noreply.github.com>